### ISSUE TITLE
New name

### ISSUE THREAD

**Issue by blegat** [JuliaAlgebra/MultivariateBases.jl#1]
PolynomailBases is already taken by https://github.com/ranocha/PolynomialBases.jl
What should be the new name ?

* MultivariateBases ?
* MultivariatePolynomialBases ?

cc @tweisser @chriscoey @lkapelevich

**Comment by tweisser** [comment]
I vote for MultivariateBases. 
MultivariatePolynomialBases would somehow imply that this packages is a multivariate version of PolynomialBases.

**Comment by lkapelevich** [comment]
I would vote for MutlivariateBases because it's shorter. It may as well be claimed.

**Comment by chriscoey** [comment]
No strong preference from me
